#! /usr/bin/env node
/**
 * Generates docs/THIRD_PARTY_NOTICES.md from the installed production
 * dependency tree. Notice preservation is a redistribution requirement of the
 * permissive licenses this project depends on; this file is regenerated
 * whenever the lockfile changes.
 */
import { createWriteStream, readFileSync } from "node:fs";
import { execFileSync } from "node:child_process";
import { join } from "node:path";

const root = process.cwd();
const outputArgument = process.argv[2] ?? "docs/THIRD_PARTY_NOTICES.md";

function licenseOf(packageDirectory) {
  const manifest = JSON.parse(readFileSync(join(packageDirectory, "package.json"), "utf8"));
  const license = typeof manifest.license === "string"
    ? manifest.license
    : Array.isArray(manifest.license)
      ? manifest.license.join(" OR ")
      : "(declared in registry metadata)";
  const repository = typeof manifest.repository === "object" && manifest.repository !== null
    ? manifest.repository.url
    : manifest.repository;
  const homepage = manifest.homepage ?? repository ?? "";
  return { name: manifest.name, version: manifest.version, license, homepage: String(homepage).replace(/^git\+/, "").replace(/\.git$/, "") };
}

const raw = execFileSync("npm", ["ls", "--all", "--omit=dev", "--json", "--long"], { cwd: root, encoding: "utf8", maxBuffer: 256 * 1024 * 1024 });
const tree = JSON.parse(raw);
const seen = new Map();
function walk(node) {
  for (const [name, dependency] of Object.entries(node.dependencies ?? {})) {
    // npm ls emits phantom entries (declared but not installed) with no path or version; skip them.
    if (!dependency.path || !dependency.version) {
      walk(dependency);
      continue;
    }
    if (!seen.has(`${name}@${dependency.version}`)) {
      try {
        seen.set(`${name}@${dependency.version}`, licenseOf(dependency.path));
      } catch {
        seen.set(`${name}@${dependency.version}`, { name, version: dependency.version, license: "(unreadable manifest)", homepage: "" });
      }
    }
    walk(dependency);
  }
}
walk(tree);

const packages = [...seen.values()].sort((a, b) => a.name.localeCompare(b.name) || a.version.localeCompare(b.version));
const grouped = new Map();
for (const entry of packages) {
  if (!grouped.has(entry.license)) grouped.set(entry.license, []);
  grouped.get(entry.license).push(entry);
}

const out = createWriteStream(join(root, outputArgument));
out.write(`# Third-Party Notices\n\n`);
out.write(`Generated by \`node scripts/generate-notices.mjs\` from the installed production tree (npm lockfile pin). `);
out.write(`Macus Code is licensed MIT; this file preserves the license notices required by its dependencies. `);
out.write(`Regenerate whenever \`package-lock.json\` changes.\n\n`);
out.write(`Total production packages: ${packages.length}\n\n`);
for (const [license, entries] of [...grouped.entries()].sort((a, b) => a[0].localeCompare(b[0]))) {
  out.write(`## ${license} (${entries.length} packages)\n\n`);
  for (const entry of entries) {
    out.write(`- **${entry.name}** ${entry.version}${entry.homepage ? ` — ${entry.homepage}` : ""}\n`);
  }
  out.write(`\n`);
}
out.end(() => console.log(`Wrote ${outputArgument} (${packages.length} packages, ${grouped.size} license groups)`));
